### ISSUE TITLE
Create test functions that allow to compare arrays

### ISSUE THREAD

**Issue by EvilLord666** [Wissance/gwuu#4]
We should create help functions for comparison primitive data types:
- array of strings (with order option and case invariant option)
- array of integers (with order option) <- however here we have a problem with bunch of integer types
- array of float (with order option)
- array of complex (with order option)

**Comment by stdstring** [comment]
> array of float (with order option)

Don't forget about correctness of float number comparison

**Comment by EvilLord666** [comment]
done
